// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
//Sesuai sama api di firebase
static const FirebaseOptions web = FirebaseOptions(
  apiKey: 'AIzaSyB9mrlJcR6-lM9E3sVKLduDPBTjWFHQlSY',
  appId: '1:781158779219:web:e1592b9d27feeee3b879a6',
  messagingSenderId: '781158779219',
  projectId: 'projekdina-e7ecd',
  authDomain: 'projekdina-e7ecd.firebaseapp.com',
  storageBucket: 'projekdina-e7ecd.firebasestorage.app',
);

static const FirebaseOptions android = FirebaseOptions(
  apiKey: 'AIzaSyB9mrlJcR6-lM9E3sVKLduDPBTjWFHQlSY',
  appId: '1:781158779219:android:e0b54ae542acc47ab879a6',
  messagingSenderId: '781158779219',
  projectId: 'projekdina-e7ecd',
  storageBucket: 'projekdina-e7ecd.firebasestorage.app',
);
}
